/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TOG;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Admin
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_Conexion = new javax.swing.JDialog();
        jl_red2 = new javax.swing.JLabel();
        cbx_nodo1 = new javax.swing.JComboBox();
        cbx_nodo2 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jl_red1 = new javax.swing.JLabel();
        jl_red11 = new javax.swing.JLabel();
        jl_red22 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        js_longitud = new javax.swing.JSpinner();
        js_ancho1 = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        js_ancho2 = new javax.swing.JSpinner();
        jb_NuevaConexion = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        cbx_material = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jp_Grafo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jd_Conexion.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                jd_ConexionWindowActivated(evt);
            }
        });
        jd_Conexion.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_red2.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        jl_red2.setForeground(new java.awt.Color(255, 255, 255));
        jl_red2.setText("Red2");
        jd_Conexion.getContentPane().add(jl_red2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 260, 50));

        cbx_nodo1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cbx_nodo1.setForeground(new java.awt.Color(0, 51, 153));
        cbx_nodo1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_nodo1ItemStateChanged(evt);
            }
        });
        jd_Conexion.getContentPane().add(cbx_nodo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 260, 50));

        cbx_nodo2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cbx_nodo2.setForeground(new java.awt.Color(0, 51, 153));
        cbx_nodo2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_nodo2ItemStateChanged(evt);
            }
        });
        jd_Conexion.getContentPane().add(cbx_nodo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 260, 50));

        jLabel7.setFont(new java.awt.Font("Impact", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/usb-cable_2-128.png"))); // NOI18N
        jLabel7.setText("  N U E V A  C O N E X I O N");
        jd_Conexion.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 650, 130));

        jl_red1.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        jl_red1.setForeground(new java.awt.Color(255, 255, 255));
        jl_red1.setText("Red1");
        jd_Conexion.getContentPane().add(jl_red1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 270, 50));

        jl_red11.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        jl_red11.setForeground(new java.awt.Color(255, 255, 255));
        jl_red11.setText("Red1");
        jd_Conexion.getContentPane().add(jl_red11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 270, 50));

        jl_red22.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        jl_red22.setForeground(new java.awt.Color(255, 255, 255));
        jl_red22.setText("Red2");
        jd_Conexion.getContentPane().add(jl_red22, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, 260, 50));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/arrow-up-64 - Copy.png"))); // NOI18N
        jd_Conexion.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 70, 70));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/arrow-up-64 - Copy - Copy.png"))); // NOI18N
        jd_Conexion.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, 70, 70));

        js_longitud.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        js_longitud.setModel(new javax.swing.SpinnerNumberModel());
        js_longitud.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jd_Conexion.getContentPane().add(js_longitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 630, 70, 50));

        js_ancho1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        js_ancho1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), null, Integer.valueOf(100), Integer.valueOf(1)));
        js_ancho1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jd_Conexion.getContentPane().add(js_ancho1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 420, 70, 50));

        jLabel13.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Escoger las Redes:");
        jd_Conexion.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 310, 80));

        jLabel14.setFont(new java.awt.Font("Poor Richard", 0, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Ingresar el Material:");
        jd_Conexion.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        js_ancho2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        js_ancho2.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), null, Integer.valueOf(100), Integer.valueOf(1)));
        js_ancho2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jd_Conexion.getContentPane().add(js_ancho2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 530, 70, 50));

        jb_NuevaConexion.setBackground(new java.awt.Color(255, 255, 255));
        jb_NuevaConexion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/011_yes-128.png"))); // NOI18N
        jb_NuevaConexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_NuevaConexionMouseClicked(evt);
            }
        });
        jd_Conexion.getContentPane().add(jb_NuevaConexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 610, 150, 90));

        jLabel17.setFont(new java.awt.Font("Poor Richard", 0, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Ingresar la Longitud:");
        jd_Conexion.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, -1, -1));

        cbx_material.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cbx_material.setForeground(new java.awt.Color(0, 51, 153));
        cbx_material.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cobre", "Fibra" }));
        cbx_material.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_materialItemStateChanged(evt);
            }
        });
        jd_Conexion.getContentPane().add(cbx_material, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 280, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background_spots_black_gray_65536_1920x1080.jpg"))); // NOI18N
        jd_Conexion.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 900, 600));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/38.jpg"))); // NOI18N
        jd_Conexion.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 170));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Poor Richard", 1, 70)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Communities__Networks-128.png"))); // NOI18N
        jLabel1.setText("   T O G O  M A P P E R");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 930, 130));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/38.jpg"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_GrafoLayout = new javax.swing.GroupLayout(jp_Grafo);
        jp_Grafo.setLayout(jp_GrafoLayout);
        jp_GrafoLayout.setHorizontalGroup(
            jp_GrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 820, Short.MAX_VALUE)
        );
        jp_GrafoLayout.setVerticalGroup(
            jp_GrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 460, Short.MAX_VALUE)
        );

        getContentPane().add(jp_Grafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 820, 460));

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/678084-folder-64.png"))); // NOI18N
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 79, -1));

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/678092-sign-add-64.png"))); // NOI18N
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 79, -1));

        jButton5.setBackground(new java.awt.Color(102, 102, 102));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/floppy-64.png"))); // NOI18N
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 79, -1));

        jLabel4.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("<html>S  E  L  E  C  C  I  O  N  A  R<br>A  N  A  L  I  S  I  S</html>");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 90, 330, 100));

        jButton8.setBackground(new java.awt.Color(153, 153, 0));
        jButton8.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 0, 51));
        jButton8.setText("Agregar Conexion");
        jButton8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton8MouseMoved(evt);
            }
        });
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 600, 190, 60));

        jButton3.setBackground(new java.awt.Color(51, 0, 51));
        jButton3.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/08_-_Earth-64.png"))); // NOI18N
        jButton3.setText("     Arbol de Redes   ");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 400, 320, 80));

        jButton7.setBackground(new java.awt.Color(51, 0, 51));
        jButton7.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/11_-_Distance-64.png"))); // NOI18N
        jButton7.setText("    Distancia mas Corta");
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 200, 320, 80));

        jButton9.setBackground(new java.awt.Color(51, 0, 51));
        jButton9.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/01_-_Globe-64.png"))); // NOI18N
        jButton9.setText(" Mayor Ancho de Banda");
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 300, 320, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/texture-blue-color-tint-background-wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1550, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        int x = evt.getX();
        int y = evt.getY();

        String[] tipoRed = {"Repetidor de Red Doméstica", "Repetidor de Red Empresarial", "Antena Celular", "Conexión Dedicada"};
        String tipo;
        if (numeroNodo == 1) {
            JOptionPane.showMessageDialog(this, "Ha ingresado la Red Central");
            tipo = "Red Central";
        } else {
            tipo = (String) JOptionPane.showInputDialog(this,
                    "Seleccione el tipo de red",
                    "Nueva Red",
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    tipoRed,
                    tipoRed[0]);
        }

        String nombre = JOptionPane.showInputDialog(
                this,
                "Ingrese el nombre de la red:",
                "Nueva Red",
                JOptionPane.PLAIN_MESSAGE);

        grafo.addVertex(new nodo_g(nombre, tipo, numeroNodo, x - 10, y - 10));

        numeroNodo++;

        try {
            grafico();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        grafo = new grafo();
        try {
            grafico();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        if (jButton8.isEnabled()) {
            this.jd_Conexion.setModal(true);
            this.jd_Conexion.pack();
            this.jd_Conexion.setVisible(true);
        }
    }//GEN-LAST:event_jButton8MouseClicked

    private void jd_ConexionWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_ConexionWindowActivated
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 1; i < grafo.getNodos().size(); i++) {
            modelo.addElement((nodo_g) grafo.getNodos().at(i));
        }
        DefaultComboBoxModel modelo1 = new DefaultComboBoxModel();
        for (int i = 1; i < grafo.getNodos().size(); i++) {
            modelo1.addElement((nodo_g) grafo.getNodos().at(i));
        }
        this.cbx_nodo1.setModel(modelo1);
        this.cbx_nodo2.setModel(modelo);

        String nombre1 = ((nodo_g) modelo.getSelectedItem()).value;
        jl_red1.setText(nombre1);
        jl_red11.setText(nombre1);
        String nombre2 = ((nodo_g) modelo1.getSelectedItem()).value;
        jl_red2.setText(nombre2);
        jl_red22.setText(nombre2);

    }//GEN-LAST:event_jd_ConexionWindowActivated

    private void cbx_nodo1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_nodo1ItemStateChanged
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cbx_nodo1.getModel();
        String nombre1 = ((nodo_g) modelo.getSelectedItem()).value;
        jl_red1.setText(nombre1);
        jl_red11.setText(nombre1);

    }//GEN-LAST:event_cbx_nodo1ItemStateChanged

    private void cbx_nodo2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_nodo2ItemStateChanged
        DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) cbx_nodo2.getModel();
        String nombre2 = ((nodo_g) modelo2.getSelectedItem()).value;
        jl_red2.setText(nombre2);
        jl_red22.setText(nombre2);
    }//GEN-LAST:event_cbx_nodo2ItemStateChanged

    private void cbx_materialItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_materialItemStateChanged
        SpinnerModel sm = new SpinnerNumberModel(0, 0, 100, 1); //default value,lower bound,upper bound,increment by
        SpinnerModel sm2 = new SpinnerNumberModel(0, 0, 20, 1); //default value,lower bound,upper bound,increment by
        DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) cbx_material.getModel();
        String nombre2 = modelo2.getSelectedItem().toString();
        if (nombre2.equals("Cobre")) {
            js_ancho1.setModel(sm);
            js_ancho2.setModel(sm);
        } else {
            js_ancho1.setModel(sm2);
            js_ancho2.setModel(sm2);
        }
    }//GEN-LAST:event_cbx_materialItemStateChanged

    private void jb_NuevaConexionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_NuevaConexionMouseClicked
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cbx_nodo1.getModel();
        nodo_g Nodo1 = ((nodo_g) modelo.getSelectedItem());
        DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) cbx_nodo2.getModel();
        nodo_g Nodo2 = ((nodo_g) modelo2.getSelectedItem());
        DefaultComboBoxModel modelo3 = (DefaultComboBoxModel) cbx_material.getModel();
        String material = modelo3.getSelectedItem().toString();
        arista arista1 = new arista((int) js_longitud.getValue(), (int) js_ancho1.getValue(), (int) js_ancho2.getValue(), material);
        arista1.setInicio(Nodo1);
        arista1.setFin(Nodo2);
        int pos1 = grafo.getNodos().find(Nodo1);
        int pos2 = grafo.getNodos().find(Nodo2);
        ((nodo_g) grafo.getNodos().at(pos1)).getAristas().push_back(arista1);
        ((nodo_g) grafo.getNodos().at(pos2)).getAristas().push_back(arista1);

        try {
            grafico();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jb_NuevaConexionMouseClicked

    private void jButton8MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseMoved
        if (grafo.nodos.size() < 2) {
            jButton8.setEnabled(false);
        } else {
            jButton8.setEnabled(true);
        }
    }//GEN-LAST:event_jButton8MouseMoved

    public void grafico() throws IOException {
        Font font = new Font("Dialog", Font.BOLD, 14);
        Graphics g = this.jp_Grafo.getGraphics();
        g.setFont(font);

        for (int i = 0; i < grafo.getNodos().size(); i++) {
            String tipo = ((nodo_g) grafo.getNodos().at(i)).tipo;
            Image imagen = null;
            switch (tipo) {
                case "Red Central": {
                    font = new Font("Dialog", Font.BOLD, 16);
                    imagen = ImageIO.read(new File("C:\\Users\\Admin\\TOGO\\TOGO\\src\\Images\\Black_ball.png"));
                    break;
                }
                case "Repetidor de Red Doméstica":
                    imagen = ImageIO.read(new File("C:\\Users\\Admin\\TOGO\\TOGO\\src\\Images\\Grey_ball.png"));
                    break;
                case "Repetidor de Red Empresarial":
                    imagen = ImageIO.read(new File("C:\\Users\\Admin\\TOGO\\TOGO\\src\\Images\\Green_ball.png"));
                    break;
                case "Antena Celular":
                    imagen = ImageIO.read(new File("C:\\Users\\Admin\\TOGO\\TOGO\\src\\Images\\Blue_ball.png"));
                    break;
                case "Conexión Dedicada":
                    imagen = ImageIO.read(new File("C:\\Users\\Admin\\TOGO\\TOGO\\src\\Images\\Aqua_ball.png"));
                    break;
            }
            g.drawImage(imagen, ((nodo_g) grafo.getNodos().at(i)).getX(), ((nodo_g) grafo.getNodos().at(i)).getY(), this);

        }

        int nodo1, nodo2;
        for (int i = 0; i < grafo.getNodos().size(); i++) {
            for (int j = 0; j < ((nodo_g) grafo.getNodos().at(i)).getAristas().size(); j++) {
                try {
                    nodo1 = (((arista) ((nodo_g) grafo.getNodos().at(i)).getAristas().at(j)).getInicio().numero) - 1;
                    nodo2 = (((arista) ((nodo_g) grafo.getNodos().at(i)).getAristas().at(j)).getFin().numero) - 1;
                    g.setColor(Color.GRAY);
                    g.drawLine(((nodo_g) grafo.getNodos().at(nodo1)).getX() + 15,
                            ((nodo_g) grafo.getNodos().at(nodo1)).getY() + 15,
                            ((nodo_g) grafo.getNodos().at(nodo2)).getX() + 15,
                            ((nodo_g) grafo.getNodos().at(nodo2)).getY() + 15);
                    g.setColor(Color.BLUE);

                    g.drawString(Long.toString(((arista) ((nodo_g) grafo.getNodos().at(i)).getAristas().at(j)).getLongitud()),
                            ((((nodo_g) grafo.getNodos().at(nodo1)).getX() + 15) + (((nodo_g) grafo.getNodos().at(nodo2)).getX() + 15)) / 2, ((((nodo_g) grafo.getNodos().at(nodo1)).getY() + 15) + (((nodo_g) grafo.getNodos().at(nodo2)).getY() + 15)) / 2);
                    g.setColor(Color.BLUE);

                } catch (Exception e) {
                }
            }
        }
        for (int i = 0; i < grafo.getNodos().size(); i++) {
            g.setColor(Color.BLACK);
            g.drawString(((nodo_g) grafo.getNodos().at(i)).getValue(), ((nodo_g) grafo.getNodos().at(i)).getX() + 10, ((nodo_g) grafo.getNodos().at(i)).getY() + 18);

        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbx_material;
    private javax.swing.JComboBox cbx_nodo1;
    private javax.swing.JComboBox cbx_nodo2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jb_NuevaConexion;
    private javax.swing.JDialog jd_Conexion;
    private javax.swing.JLabel jl_red1;
    private javax.swing.JLabel jl_red11;
    private javax.swing.JLabel jl_red2;
    private javax.swing.JLabel jl_red22;
    private javax.swing.JPanel jp_Grafo;
    private javax.swing.JSpinner js_ancho1;
    private javax.swing.JSpinner js_ancho2;
    private javax.swing.JSpinner js_longitud;
    // End of variables declaration//GEN-END:variables

    grafo grafo = new grafo();
    
    int numeroNodo = 1;

}
