/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TOG;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jp_Grafo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Poor Richard", 1, 70)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Communities__Networks-128.png"))); // NOI18N
        jLabel1.setText("   T O G O  M A P P E R");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 930, 140));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/38.jpg"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_GrafoLayout = new javax.swing.GroupLayout(jp_Grafo);
        jp_Grafo.setLayout(jp_GrafoLayout);
        jp_GrafoLayout.setHorizontalGroup(
            jp_GrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_GrafoLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jp_GrafoLayout.setVerticalGroup(
            jp_GrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 600, Short.MAX_VALUE)
        );

        getContentPane().add(jp_Grafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 1050, 600));

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/678084-folder-64.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 79, -1));

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/678092-sign-add-64.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 79, -1));

        jButton5.setBackground(new java.awt.Color(102, 102, 102));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/floppy-64.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 79, -1));

        jLabel4.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("<html>S  E  L  E  C  C  I  O  N  A  R<br>A  N  A  L  I  S  I  S</html>");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 130, 330, 100));

        jButton8.setBackground(new java.awt.Color(153, 153, 0));
        jButton8.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 0, 51));
        jButton8.setText("Agregar Conexion");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 800, 190, 60));

        jButton3.setBackground(new java.awt.Color(51, 0, 51));
        jButton3.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/08_-_Earth-64.png"))); // NOI18N
        jButton3.setText("     Arbol de Redes   ");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 440, 320, 80));

        jButton7.setBackground(new java.awt.Color(51, 0, 51));
        jButton7.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/11_-_Distance-64.png"))); // NOI18N
        jButton7.setText("    Distancia mas Corta");
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 240, 320, 80));

        jButton9.setBackground(new java.awt.Color(51, 0, 51));
        jButton9.setFont(new java.awt.Font("Rockwell Condensed", 0, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/01_-_Globe-64.png"))); // NOI18N
        jButton9.setText(" Mayor Ancho de Banda");
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 340, 320, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/texture-blue-color-tint-background-wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1550, 910));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        int x = evt.getX();
        int y = evt.getY();

        String[] tipoRed = {"Repetidor de Red Doméstica", "Repetidor de Red Empresarial", "Antena Celular", "Conexión Dedicada"};
        String tipo;
        if (numeroNodo == 1) {
            JOptionPane.showMessageDialog(this, "Ha ingresado la Red Central");
            tipo = "Red Central";
        } else {
            tipo = (String) JOptionPane.showInputDialog(this,
                    "Seleccione el tipo de red",
                    "Nueva Red",
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    tipoRed,
                    tipoRed[0]);
        }

        String nombre = JOptionPane.showInputDialog(
                this,
                "Ingrese el nombre de la red:",
                "Nueva Red",
                JOptionPane.PLAIN_MESSAGE);

        grafo.addVertex(new nodo_g(nombre, tipo, numeroNodo, x - 10, y - 10));

        

        numeroNodo++;

        try {
            refresh();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        
    }//GEN-LAST:event_jButton8ActionPerformed

    public void refresh() throws IOException {
        
        Font font = new Font("Dialog", Font.BOLD, 14);
        Graphics g = this.jp_Grafo.getGraphics();
        g.setFont(font);

        for (int i = 0; i < grafo.getNodos().size(); i++) {
            String tipo = ((nodo_g)grafo.getNodos().at(i)).tipo;
            Image imagen= null;
            switch(tipo){
                case "Nueva Red":
                     imagen= ImageIO.read(new File("C:\\Users\\Admin\\TOGO\\TOGO\\src\\Images\\Black_ball.png"));
                    break;
                case "Repetidor de Red Doméstica":
                    imagen= ImageIO.read(new File("C:\\Users\\Admin\\TOGO\\TOGO\\src\\Images\\Grey_ball.png"));
                    break;
                case "Repetidor de Red Empresarial":
                    imagen= ImageIO.read(new File("C:\\Users\\Admin\\TOGO\\TOGO\\src\\Images\\Green_ball.png"));
                    break;
                case "Antena Celular":
                    imagen= ImageIO.read(new File("C:\\Users\\Admin\\TOGO\\TOGO\\src\\Images\\Blue_ball.png"));
                    break;
                case "Conexión Dedicada":
                    imagen= ImageIO.read(new File("C:\\Users\\Admin\\TOGO\\TOGO\\src\\Images\\Aqua_ball.png"));
                    break;
            }
            g.drawImage(imagen,((nodo_g)grafo.getNodos().at(i)).getX(),((nodo_g)grafo.getNodos().at(i)).getY(), this);
            
        }

        int nodo1, nodo2;

        for (int i = 0; i < grafo.getNodos().size(); i++) {
            for (int j = 0; j < ((nodo_g)grafo.getNodos().at(i)).getAristas().size(); j++) {
                try {
                    nodo1 = (((arista)((nodo_g)grafo.getNodos().at(i)).getAristas().at(j)).getInicio().numero)-1;
                    nodo2 = (((arista)((nodo_g)grafo.getNodos().at(i)).getAristas().at(j)).getFin().numero)-1;
                    g.setColor(Color.RED);
                    g.drawLine(((nodo_g)grafo.getNodos().at(nodo1)).getX() + 15,
                            ((nodo_g)grafo.getNodos().at(nodo1)).getY() + 15,
                            ((nodo_g)grafo.getNodos().at(nodo2)).getX() + 15,
                            ((nodo_g)grafo.getNodos().at(nodo2)).getY() + 15);
                    g.setColor(Color.GRAY);
                    
                    g.drawString(Long.toString(((arista)((nodo_g)grafo.getNodos().at(i)).getAristas().at(j)).getLongitud()),
                            ((((nodo_g)grafo.getNodos().at(nodo1)).getX() + 15) + (((nodo_g)grafo.getNodos().at(nodo2)).getX() + 15)) / 2, ((((nodo_g)grafo.getNodos().at(nodo1)).getY() + 15) + (((nodo_g)grafo.getNodos().at(nodo2)).getY() + 15)) / 2);
                    g.setColor(Color.BLUE);

                } catch (Exception e) {
                }
            }
        }
    }
    
    public void grafico(){
        Font font = new Font("Serif", Font.BOLD, 14);
        Graphics g = this.jp_Grafo.getGraphics();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jp_Grafo;
    // End of variables declaration//GEN-END:variables

    grafo grafo = new grafo();
    int numeroNodo = 1;

}
